### ISSUE TITLE
Plan for 1.0.0

### ISSUE THREAD

**Issue by ruimarinho** [seegno/is-valid-ein#2]
- [x] Remove lodash dependency.
- [x] Rename to `ein-validator`.
- [x] Add `strict` mode option to `isValid` to consider dashes and spaces when validating or not.
- [x] Add node 5 to the test matrix (https://github.com/seegno/is-valid-ein/blob/master/.travis.yml#L4) or consider using `docker-compose run --rm sut`.
- [x] Add missing "Instances" comment (https://github.com/seegno/is-valid-ein/blob/master/src/index.js#L38).
- [x] Convert to ES2015 template string (https://github.com/seegno/is-valid-ein/blob/master/src/index.js#L64).
- [x] Fix README typos (e.g. "This modules allows you to check if a number is a valid")
- [x] Invert order of "See" with the introduction (https://github.com/seegno/is-valid-ein/blob/master/src/index.js#L3).
- [x] Update package.json (e.g. based on [this](https://github.com/seegno/bitcoin-core/blob/master/package.json) one), with special focus on scripts.
- [x] Update README to include lodash-like arguments (based on [this](https://github.com/seegno/bitcoin-core/blob/master/README.md)).
- [x] Update `eslint-config-seegno` to 2.0.0 and subsequently the [rc file](https://github.com/seegno/is-valid-ein/blob/master/.eslintrc#L1), including renaming to yml.
- [x] Export named functions instead (https://github.com/seegno/is-valid-ein/blob/master/src/index.js#L71).

**Comment by ruimarinho** [comment]
Bump.

**Comment by franciscocardoso** [comment]
Refs https://github.com/seegno/is-valid-ein/pull/4.

**Comment by ruimarinho** [comment]
Closes #5.
